window.photoCenterCalculatorData = {
  version: "1.1.0",
  referenceCatalogs: {
    photoFrames: {
      A6: 100,
      A5: 200,
      A4: 300,
    },
  },
  pricingModes: [
    "fixed",
    "tiered",
    "variant_fixed",
    "variant_tiered",
    "surcharge",
    "requires_confirmation",
  ],
  manualPromos: [
    {
      id: "review_discount",
      title: "Отзыв на Яндекс Картах",
      discountType: "percent",
      value: 15,
      scope: "next_order",
      notes: [
        "Скидка действует на следующий заказ.",
        "По текущим условиям суммируется с акциями 5% и 10%.",
      ],
    },
    {
      id: "photo_plus_frame",
      title: "Фото + рамка",
      discountType: "percent",
      value: 15,
      scope: "bundle",
      notes: ["Применяется при совместном заказе фото и рамки."],
    },
    {
      id: "photo_plus_lamination",
      title: "Фото + ламинация",
      discountType: "percent",
      value: 10,
      scope: "bundle",
      notes: ["Применяется при совместном заказе фото и ламинации."],
    },
    {
      id: "gift_bundle_two",
      title: "Комплект из 2 товаров",
      discountType: "percent",
      value: 10,
      scope: "bundle",
      notes: ["Применяется к комплекту из двух товаров."],
    },
    {
      id: "pair_mugs_or_tshirts",
      title: "Парные кружки или футболки",
      discountType: "percent",
      value: 10,
      scope: "bundle",
      notes: ["Применяется к парным кружкам или футболкам."],
    },
    {
      id: "digitization_photo_bonus",
      title: "После оцифровки печать фото 10x15",
      discountType: "percent",
      value: 10,
      scope: "followup_bundle",
      notes: ["Скидка действует на печать фото 10x15 после оцифровки."],
    },
  ],
  autoDiscounts: [
    {
      id: "photo_print_bulk",
      title: "Тиражные цены на печать фото",
      notes: ["Применяются автоматически по выбранному диапазону количества."],
    },
    {
      id: "scan_bulk",
      title: "Тиражные цены на сканирование",
      notes: ["Применяются автоматически по выбранному диапазону количества."],
    },
    {
      id: "print_bulk",
      title: "Тиражные цены на ксерокопии и распечатку",
      notes: ["Применяются автоматически по выбранному диапазону количества."],
    },
    {
      id: "lamination_bulk",
      title: "Тиражные цены на ламинирование",
      notes: ["Применяются автоматически по выбранному диапазону количества."],
    },
    {
      id: "digitization_bulk",
      title: "Тиражные цены на оцифровку",
      notes: ["Применяются автоматически по выбранному диапазону количества."],
    },
    {
      id: "souvenir_bulk",
      title: "Скидка на сувенирную печать",
      notes: ["От 3 шт. -10%, от 5 шт. -15%."],
    },
  ],
  categories: [
    {
      id: "photo",
      title: "Печать фото",
      notes: ["Основная категория для расчёта печати фото по размеру и количеству."],
      services: [
        {
          id: "photo_print_standard",
          category: "photo",
          title: "Печать фото",
          pricingMode: "variant_tiered",
          options: [
            {
              id: "a8_standard",
              title: "A8",
              parameters: {
                size: "5x7.5 см",
                paperType: "Стандартная фотопечать",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 49, price: 20, label: "1-49 шт." },
                { min: 50, max: 99, price: 18, label: "50-99 шт." },
                { min: 100, max: 199, price: 17, label: "100-199 шт." },
                { min: 200, max: null, price: 16, label: "200+ шт." },
              ],
            },
            {
              id: "a7_standard",
              title: "A7",
              parameters: {
                size: "7.5x10 см",
                paperType: "Стандартная фотопечать",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 29, price: 30, label: "1-29 шт." },
                { min: 30, max: 59, price: 27, label: "30-59 шт." },
                { min: 60, max: 99, price: 26, label: "60-99 шт." },
                { min: 100, max: null, price: 24, label: "100+ шт." },
              ],
            },
            {
              id: "a6_standard",
              title: "A6",
              parameters: {
                size: "10x15 см",
                paperType: "Стандартная фотопечать",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 9, price: 50, label: "1-9 шт." },
                { min: 10, max: 29, price: 45, label: "10-29 шт." },
                { min: 30, max: 49, price: 43, label: "30-49 шт." },
                { min: 50, max: 99, price: 40, label: "50-99 шт." },
                { min: 100, max: 199, price: 38, label: "100-199 шт." },
                { min: 200, max: null, price: 35, label: "200+ шт." },
              ],
            },
            {
              id: "13x18_standard",
              title: "13x18",
              parameters: {
                size: "13x18 см",
                paperType: "Стандартная фотопечать",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 9, price: 100, label: "1-9 шт." },
                { min: 10, max: 14, price: 90, label: "10-14 шт." },
                { min: 15, max: 29, price: 85, label: "15-29 шт." },
                { min: 30, max: null, price: 80, label: "30+ шт." },
              ],
            },
            {
              id: "a5_standard",
              title: "A5",
              parameters: {
                size: "15x20 см",
                paperType: "Стандартная фотопечать",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 9, price: 150, label: "1-9 шт." },
                { min: 10, max: 14, price: 135, label: "10-14 шт." },
                { min: 15, max: 29, price: 128, label: "15-29 шт." },
                { min: 30, max: null, price: 120, label: "30+ шт." },
              ],
            },
            {
              id: "a4_standard",
              title: "A4",
              parameters: {
                size: "21x29.7 см",
                paperType: "Стандартная фотопечать",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 4, price: 250, label: "1-4 шт." },
                { min: 5, max: 9, price: 225, label: "5-9 шт." },
                { min: 10, max: 29, price: 213, label: "10-29 шт." },
                { min: 30, max: null, price: 200, label: "30+ шт." },
              ],
            },
            {
              id: "a3_standard",
              title: "A3",
              parameters: {
                size: "29.7x42 см",
                paperType: "Стандартная фотопечать",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 2, price: 850, label: "1-2 шт." },
                { min: 3, max: 5, price: 765, label: "3-5 шт." },
                { min: 6, max: 10, price: 723, label: "6-10 шт." },
                { min: 11, max: null, price: 680, label: "11+ шт." },
              ],
            },
          ],
          tiers: [],
          adjustments: [
            {
              id: "nonstandard_crop",
              title: "Нестандартный",
              pricingMode: "surcharge",
              amount: 15,
              parameters: {
                size: "По макету",
                paperType: "Кадрирование",
              },
            },
          ],
          autoDiscounts: ["photo_print_bulk"],
          manualPromos: [
            "review_discount",
            "photo_plus_frame",
            "photo_plus_lamination",
            "digitization_photo_bonus",
          ],
          notes: ["Основной расчёт строится по размеру, типу бумаги и количеству."],
        },
      ],
    },
    {
      id: "docs",
      title: "Фото на документы",
      notes: ["Категория с комплектами, ретушью и отдельными услугами по фото на документы."],
      services: [
        {
          id: "documents_main_sets",
          category: "docs",
          title: "Фото на документы",
          pricingMode: "variant_fixed",
          options: [
            {
              id: "doc_3x4_or_2x3",
              title: "Фото на документы 3x4 / 2x3",
              parameters: {
                format: "3x4 / 2x3",
                description: "Комплект 4 шт.; пропуск, студенческий, мед.книжка, военный билет и др.",
              },
              pricingMode: "fixed",
              price: 500,
            },
            {
              id: "doc_3_5x4_5",
              title: "Фото на документы 3.5x4.5",
              parameters: {
                format: "3.5x4.5",
                description: "Комплект 4 шт.",
              },
              pricingMode: "fixed",
              price: 600,
            },
            {
              id: "doc_5x5_printed",
              title: "Фото на документы 5x5 с печатью",
              parameters: {
                format: "5x5",
                description: "С печатью, 4 шт.",
              },
              pricingMode: "fixed",
              price: 800,
            },
            {
              id: "doc_5x5_digital",
              title: "Фото на документы 5x5 электронный вид",
              parameters: {
                format: "5x5",
                description: "Электронный вид, без печати",
              },
              pricingMode: "fixed",
              price: 600,
            },
            {
              id: "doc_5x5_ready",
              title: "Фото на документы 5x5 готовое фото",
              parameters: {
                format: "5x5",
                description: "Готовое фото, печать 2 шт.",
              },
              pricingMode: "fixed",
              price: 300,
            },
            {
              id: "doc_9x12_package",
              title: "Фото на документы 9x12 пакет услуг",
              parameters: {
                format: "9x12",
                description: "Пакет услуг, 1 шт.",
              },
              pricingMode: "fixed",
              price: 700,
            },
            {
              id: "doc_9x12_ready",
              title: "Фото на документы 9x12 готовое фото",
              parameters: {
                format: "9x12",
                description: "Готовое фото, 1 шт.",
              },
              pricingMode: "fixed",
              price: 300,
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: ["review_discount"],
          notes: ["Базовые комплекты документов."],
        },
        {
          id: "documents_ready_pack",
          category: "docs",
          title: "Готовый комплект",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 2, max: 2, price: 250, label: "2 шт." },
            { min: 4, max: 4, price: 350, label: "4 шт." },
            { min: 6, max: 6, price: 500, label: "6 шт." },
            { min: 8, max: 8, price: 550, label: "8 шт." },
            { min: 10, max: 10, price: 600, label: "10 шт." },
          ],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: ["Печать готовых фото на документы."],
        },
        {
          id: "documents_extra_pack",
          category: "docs",
          title: "Дополнительный комплект",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 2, max: 2, price: 150, label: "2 шт." },
            { min: 4, max: 4, price: 200, label: "4 шт." },
            { min: 6, max: 6, price: 350, label: "6 шт." },
            { min: 8, max: 8, price: 450, label: "8 шт." },
            { min: 10, max: 10, price: 500, label: "10 шт." },
          ],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: ["Дополнительная печать к комплекту."],
        },
        {
          id: "documents_addons",
          category: "docs",
          title: "Дополнительные услуги для фото на документы",
          pricingMode: "variant_fixed",
          options: [
            {
              id: "uniform_overlay",
              title: "Подстановка костюма",
              parameters: {
                format: "Для фото",
                description: "Служебные формы со званиями, классическая мужская и женская одежда",
              },
              pricingMode: "fixed",
              price: 150,
            },
            {
              id: "digital_photo",
              title: "Электронное фото",
              parameters: {
                format: "Файл",
                description: "Сфотографировать и обработать фото",
              },
              pricingMode: "fixed",
              price: 450,
            },
            {
              id: "waist_photo_processing",
              title: "Фото по пояс, обработка",
              parameters: {
                format: "1 фото",
                description: "Сфотографировать по пояс, обработать. Бонус: печать фото 10x15",
              },
              pricingMode: "fixed",
              price: 600,
            },
            {
              id: "retouch_color",
              title: "Ретушь фото",
              parameters: {
                format: "1 элемент",
                description: "Цветокоррекция, покраснение",
              },
              pricingMode: "fixed",
              price: 80,
            },
            {
              id: "retouch_background",
              title: "Ретушь фото",
              parameters: {
                format: "1 элемент",
                description: "Фон, удаление элемента",
              },
              pricingMode: "fixed",
              price: 150,
            },
            {
              id: "photo_restore_work",
              title: "Работа с фото",
              parameters: {
                format: "1 элемент",
                description: "Восстановление",
              },
              pricingMode: "fixed",
              price: 500,
            },
            {
              id: "photo_restoration_full",
              title: "Реставрация фото",
              parameters: {
                format: "1 фото",
                description: "Полный пакет",
              },
              pricingMode: "fixed",
              price: 850,
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: ["review_discount"],
          notes: ["Дополнительные услуги по ретуши и подготовке фото."],
        },
      ],
    },
    {
      id: "digital",
      title: "Оцифровка",
      notes: ["Категория для видеокассет, фотоплёнки и сопутствующих услуг."],
      services: [
        {
          id: "video_digitization",
          category: "digital",
          title: "Оцифровка видеокассет",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 1, max: 99, price: 20, label: "1-99 мин." },
            { min: 100, max: 299, price: 19, label: "100-299 мин." },
            { min: 300, max: null, price: 18, label: "300+ мин." },
          ],
          adjustments: [],
          autoDiscounts: ["digitization_bulk"],
          manualPromos: [],
          notes: [
            "Цена указана за минуту записи.",
            "Минимальная стоимость кассеты - 900 ₽.",
          ],
        },
        {
          id: "film_digitization",
          category: "digital",
          title: "Оцифровка фотоплёнки",
          pricingMode: "variant_tiered",
          options: [
            {
              id: "film_budget",
              title: "Оцифровка фотоплёнки budget",
              parameters: {
                mode: "Budget",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 2, price: 850, label: "1-2 шт." },
                { min: 3, max: 9, price: 808, label: "3-9 шт." },
                { min: 10, max: null, price: 765, label: "10+ шт." },
              ],
            },
            {
              id: "film_standard",
              title: "Оцифровка фотоплёнки standard",
              parameters: {
                mode: "Standard",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 2, price: 950, label: "1-2 шт." },
                { min: 3, max: 9, price: 903, label: "3-9 шт." },
                { min: 10, max: null, price: 855, label: "10+ шт." },
              ],
            },
            {
              id: "film_max",
              title: "Оцифровка фотоплёнки max",
              parameters: {
                mode: "MAX",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 2, price: 1200, label: "1-2 шт." },
                { min: 3, max: 9, price: 1140, label: "3-9 шт." },
                { min: 10, max: null, price: 1080, label: "10+ шт." },
              ],
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: ["digitization_bulk"],
          manualPromos: [],
          notes: ["Оцифровка по катушкам с несколькими режимами качества."],
        },
        {
          id: "film_processing",
          category: "digital",
          title: "Проявка фотоплёнки",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 1, max: 2, price: 550, label: "1-2 шт." },
            { min: 3, max: 9, price: 523, label: "3-9 шт." },
            { min: 10, max: null, price: 495, label: "10+ шт." },
          ],
          adjustments: [],
          autoDiscounts: ["digitization_bulk"],
          manualPromos: [],
          notes: [],
        },
        {
          id: "film_scanning",
          category: "digital",
          title: "Сканирование фотоплёнки",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 1, max: 2, price: 700, label: "1-2 шт." },
            { min: 3, max: 9, price: 665, label: "3-9 шт." },
            { min: 10, max: null, price: 630, label: "10+ шт." },
          ],
          adjustments: [],
          autoDiscounts: ["digitization_bulk"],
          manualPromos: [],
          notes: [],
        },
        {
          id: "cut_frame",
          category: "digital",
          title: "Порезанный кадр",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 1, max: 9, price: 80, label: "1-9 шт." },
            { min: 10, max: 29, price: 76, label: "10-29 шт." },
            { min: 30, max: null, price: 72, label: "30+ шт." },
          ],
          adjustments: [],
          autoDiscounts: ["digitization_bulk"],
          manualPromos: [],
          notes: [],
        },
        {
          id: "digitization_addons",
          category: "digital",
          title: "Дополнительные услуги оцифровки",
          pricingMode: "variant_fixed",
          options: [
            {
              id: "extract_film",
              title: "Вытащить фотоплёнку",
              parameters: {
                mode: "1 шт.",
              },
              pricingMode: "fixed",
              price: 250,
            },
            {
              id: "storage_digitization",
              title: "Оцифровка с накопителя",
              parameters: {
                mode: "1 ГБ",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 4, price: 150, label: "1-4 ГБ" },
                { min: 5, max: 19, price: 143, label: "5-19 ГБ" },
                { min: 20, max: 49, price: 135, label: "20-49 ГБ" },
                { min: 50, max: null, price: 128, label: "50+ ГБ" },
              ],
            },
            {
              id: "disk_cd_dvd",
              title: "Диск CD / DVD",
              parameters: {
                mode: "Товар",
              },
              pricingMode: "fixed",
              price: 100,
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: ["digitization_photo_bonus"],
          notes: ["После оцифровки печать фото 10x15 -10%."],
        },
      ],
    },
    {
      id: "scan",
      title: "Сканирование",
      notes: ["Категория для документов, фото и отдельных цифровых файлов."],
      services: [
        {
          id: "document_scanning",
          category: "scan",
          title: "Сканирование документа",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 1, max: 19, price: 20, label: "1-19 шт." },
            { min: 20, max: 49, price: 19, label: "20-49 шт." },
            { min: 50, max: null, price: 18, label: "50+ шт." },
          ],
          adjustments: [],
          autoDiscounts: ["scan_bulk"],
          manualPromos: [],
          notes: [],
        },
        {
          id: "file_send",
          category: "scan",
          title: "Отправка файла",
          pricingMode: "fixed",
          options: [],
          tiers: [],
          adjustments: [],
          price: 10,
          autoDiscounts: [],
          manualPromos: [],
          notes: [],
        },
        {
          id: "photo_scan_a4_600dpi",
          category: "scan",
          title: "Сканирование фото A4, 600 dpi",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 1, max: 9, price: 50, label: "1-9 шт." },
            { min: 10, max: 19, price: 48, label: "10-19 шт." },
            { min: 20, max: 49, price: 45, label: "20-49 шт." },
            { min: 50, max: null, price: 43, label: "50+ шт." },
          ],
          adjustments: [],
          autoDiscounts: ["scan_bulk"],
          manualPromos: [],
          notes: [],
        },
        {
          id: "photo_digitization_processed",
          category: "scan",
          title: "Оцифровка фото с обработкой",
          pricingMode: "variant_fixed",
          options: [
            {
              id: "photo_digitization_1200",
              title: "Оцифровка фото с обработкой 1200 dpi",
              parameters: {
                dpi: "1200 dpi",
                description: "Сканирование, кадрирование, цветокоррекция",
              },
              pricingMode: "fixed",
              price: 170,
            },
            {
              id: "photo_digitization_2400",
              title: "Оцифровка фото с обработкой 2400 dpi",
              parameters: {
                dpi: "2400 dpi",
                description: "Сканирование, кадрирование, цветокоррекция",
              },
              pricingMode: "fixed",
              price: 220,
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: [],
        },
      ],
    },
    {
      id: "print",
      title: "Ксерокопии и распечатка",
      notes: ["Категория для копий и печати с делением на ч/б и цвет."],
      services: [
        {
          id: "copy_a4",
          category: "print",
          title: "Ксерокопия A4",
          pricingMode: "variant_tiered",
          options: [
            {
              id: "copy_a4_bw",
              title: "Ксерокопия A4 Ч/б",
              parameters: {
                format: "A4",
                printType: "Черно-белое",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 29, price: 25, label: "1-29 шт." },
                { min: 30, max: 99, price: 24, label: "30-99 шт." },
                { min: 100, max: 299, price: 23, label: "100-299 шт." },
                { min: 300, max: null, price: 22, label: "300+ шт." },
              ],
            },
            {
              id: "copy_a4_color",
              title: "Ксерокопия A4 Цвет",
              parameters: {
                format: "A4",
                printType: "Цвет",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 29, price: 45, label: "1-29 шт." },
                { min: 30, max: 99, price: 43, label: "30-99 шт." },
                { min: 100, max: 299, price: 41, label: "100-299 шт." },
                { min: 300, max: null, price: 39, label: "300+ шт." },
              ],
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: ["print_bulk"],
          manualPromos: [],
          notes: [],
        },
        {
          id: "extra_roll_a4",
          category: "print",
          title: "Доп. прокат A4",
          pricingMode: "variant_fixed",
          options: [
            {
              id: "extra_roll_a4_bw",
              title: "Доп. прокат A4 Ч/б",
              parameters: {
                format: "A4",
                printType: "Черно-белое",
              },
              pricingMode: "fixed",
              price: 12,
            },
            {
              id: "extra_roll_a4_color",
              title: "Доп. прокат A4 Цвет",
              parameters: {
                format: "A4",
                printType: "Цвет",
              },
              pricingMode: "fixed",
              price: 20,
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: [],
        },
        {
          id: "print_a4",
          category: "print",
          title: "Распечатка A4",
          pricingMode: "variant_tiered",
          options: [
            {
              id: "print_a4_bw",
              title: "Распечатка A4 Ч/б",
              parameters: {
                format: "A4",
                printType: "Черно-белое",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 29, price: 20, label: "1-29 шт." },
                { min: 30, max: 99, price: 19, label: "30-99 шт." },
                { min: 100, max: 299, price: 18, label: "100-299 шт." },
                { min: 300, max: null, price: 17, label: "300+ шт." },
              ],
            },
            {
              id: "print_a4_color",
              title: "Распечатка A4 Цвет",
              parameters: {
                format: "A4",
                printType: "Цвет",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 29, price: 40, label: "1-29 шт." },
                { min: 30, max: 99, price: 38, label: "30-99 шт." },
                { min: 100, max: 299, price: 36, label: "100-299 шт." },
                { min: 300, max: null, price: 34, label: "300+ шт." },
              ],
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: ["print_bulk"],
          manualPromos: [],
          notes: [],
        },
        {
          id: "print_a3",
          category: "print",
          title: "Распечатка A3",
          pricingMode: "variant_tiered",
          options: [
            {
              id: "print_a3_bw",
              title: "Распечатка A3 Ч/б",
              parameters: {
                format: "A3",
                printType: "Черно-белое",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 19, price: 50, label: "1-19 шт." },
                { min: 20, max: 49, price: 48, label: "20-49 шт." },
                { min: 50, max: null, price: 45, label: "50+ шт." },
              ],
            },
            {
              id: "print_a3_color",
              title: "Распечатка A3 Цвет",
              parameters: {
                format: "A3",
                printType: "Цвет",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 19, price: 85, label: "1-19 шт." },
                { min: 20, max: 49, price: 81, label: "20-49 шт." },
                { min: 50, max: null, price: 77, label: "50+ шт." },
              ],
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: ["print_bulk"],
          manualPromos: [],
          notes: [],
        },
        {
          id: "extra_roll_a3",
          category: "print",
          title: "Доп. прокат A3",
          pricingMode: "variant_fixed",
          options: [
            {
              id: "extra_roll_a3_bw",
              title: "Доп. прокат A3 Ч/б",
              parameters: {
                format: "A3",
                printType: "Черно-белое",
              },
              pricingMode: "fixed",
              price: 25,
            },
            {
              id: "extra_roll_a3_color",
              title: "Доп. прокат A3 Цвет",
              parameters: {
                format: "A3",
                printType: "Цвет",
              },
              pricingMode: "fixed",
              price: 45,
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: [],
        },
        {
          id: "print_fill_adjustment",
          category: "print",
          title: "Заливка свыше 50%",
          pricingMode: "surcharge",
          options: [],
          tiers: [],
          adjustments: [
            {
              id: "fill_over_50",
              title: "Заливка свыше 50%",
              pricingMode: "surcharge",
              multiplier: 1.5,
              description: "Стоимость увеличивается на 50%",
            },
          ],
          autoDiscounts: [],
          manualPromos: [],
          notes: ["Надбавка применяется к выбранному тарифу."],
        },
      ],
    },
    {
      id: "binding",
      title: "Брошюровка",
      notes: ["Категория для брошюровки на пружину и дополнительных листов."],
      services: [
        {
          id: "binding_plastic",
          category: "binding",
          title: "Брошюровка на пластиковую пружину",
          pricingMode: "tiered",
          options: [],
          tiers: [
            { min: 1, max: 10, price: 150, label: "До 10 листов" },
            { min: 11, max: 20, price: 200, label: "До 20 листов" },
            { min: 21, max: 50, price: 300, label: "До 50 листов" },
            { min: 51, max: 100, price: 400, label: "До 100 листов" },
            { min: 101, max: 200, price: 550, label: "До 200 листов" },
            { min: 201, max: 280, price: 600, label: "До 280 листов" },
          ],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: ["Расчёт строится по количеству листов."],
        },
        {
          id: "binding_metal",
          category: "binding",
          title: "Брошюровка на металлическую пружину",
          pricingMode: "tiered",
          options: [],
          tiers: [{ min: 1, max: 20, price: 350, label: "До 20 листов" }],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: ["Для расширения потребуются дополнительные варианты."],
        },
        {
          id: "binding_sheet_replace",
          category: "binding",
          title: "Замена / доп. лист",
          pricingMode: "tiered",
          options: [],
          tiers: [{ min: 1, max: 5, price: 50, label: "До 5 листов" }],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: [],
        },
      ],
    },
    {
      id: "lamination",
      title: "Ламинирование",
      notes: ["Категория для расчёта ламинирования по формату и количеству."],
      services: [
        {
          id: "lamination_main",
          category: "lamination",
          title: "Ламинирование",
          pricingMode: "variant_tiered",
          options: [
            {
              id: "lamination_a3",
              title: "Ламинирование A3",
              parameters: {
                format: "A3",
                filmType: "Глянец",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 4, price: 375, label: "1-4 шт." },
                { min: 5, max: 14, price: 357, label: "5-14 шт." },
                { min: 15, max: null, price: 338, label: "15+ шт." },
              ],
            },
            {
              id: "lamination_a4",
              title: "Ламинирование A4",
              parameters: {
                format: "A4",
                filmType: "Глянец",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 9, price: 150, label: "1-9 шт." },
                { min: 10, max: 29, price: 143, label: "10-29 шт." },
                { min: 30, max: null, price: 135, label: "30+ шт." },
              ],
            },
            {
              id: "lamination_a5",
              title: "Ламинирование A5",
              parameters: {
                format: "A5",
                filmType: "Глянец",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 14, price: 100, label: "1-14 шт." },
                { min: 15, max: 39, price: 95, label: "15-39 шт." },
                { min: 40, max: null, price: 90, label: "40+ шт." },
              ],
            },
            {
              id: "lamination_a6",
              title: "Ламинирование A6",
              parameters: {
                format: "A6",
                filmType: "Глянец",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 19, price: 80, label: "1-19 шт." },
                { min: 20, max: 49, price: 76, label: "20-49 шт." },
                { min: 50, max: null, price: 72, label: "50+ шт." },
              ],
            },
            {
              id: "lamination_a7",
              title: "Ламинирование A7",
              parameters: {
                format: "A7",
                filmType: "Глянец",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 29, price: 50, label: "1-29 шт." },
                { min: 30, max: 79, price: 48, label: "30-79 шт." },
                { min: 80, max: null, price: 45, label: "80+ шт." },
              ],
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: ["lamination_bulk"],
          manualPromos: ["photo_plus_lamination"],
          notes: [],
        },
      ],
    },
    {
      id: "paper",
      title: "Плотная бумага",
      notes: ["Категория для матовой, меловой и глянцевой бумаги с учётом количества сторон."],
      services: [
        {
          id: "thick_paper_print",
          category: "paper",
          title: "Плотная бумага",
          pricingMode: "variant_fixed",
          options: [
            {
              id: "paper_a3_200g",
              title: "A3 200 г",
              parameters: {
                format: "A3",
                paperType: "Матовая / мелованная 200 г",
                sides: "Односторонняя",
              },
              pricingMode: "tiered",
              tiers: [
                { min: 1, max: 2, price: 110, label: "1-2 шт." },
                { min: 3, max: 5, price: 99, label: "3-5 шт." },
                { min: 6, max: 10, price: 94, label: "6-10 шт." },
                { min: 11, max: null, price: 88, label: "11+ шт." },
              ],
            },
            {
              id: "paper_a4_100_190",
              title: "A4 100-190 г",
              parameters: {
                format: "A4",
                paperType: "Матовая / меловая 100-190 г",
              },
              pricingMode: "variant_tiered",
              priceVariants: [
                {
                  id: "paper_a4_100_190_one",
                  title: "Односторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 4, price: 110, label: "1-4 шт." },
                    { min: 5, max: 9, price: 99, label: "5-9 шт." },
                    { min: 10, max: 29, price: 94, label: "10-29 шт." },
                    { min: 30, max: null, price: 88, label: "30+ шт." },
                  ],
                },
                {
                  id: "paper_a4_100_190_two",
                  title: "Двусторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 4, price: 165, label: "1-4 шт." },
                    { min: 5, max: 9, price: 149, label: "5-9 шт." },
                    { min: 10, max: 29, price: 140, label: "10-29 шт." },
                    { min: 30, max: null, price: 132, label: "30+ шт." },
                  ],
                },
              ],
            },
            {
              id: "paper_a4_200_300",
              title: "A4 200-300 г",
              parameters: {
                format: "A4",
                paperType: "Матовая / меловая 200-300 г",
              },
              pricingMode: "variant_tiered",
              priceVariants: [
                {
                  id: "paper_a4_200_300_one",
                  title: "Односторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 4, price: 140, label: "1-4 шт." },
                    { min: 5, max: 9, price: 126, label: "5-9 шт." },
                    { min: 10, max: 29, price: 119, label: "10-29 шт." },
                    { min: 30, max: null, price: 112, label: "30+ шт." },
                  ],
                },
                {
                  id: "paper_a4_200_300_two",
                  title: "Двусторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 4, price: 210, label: "1-4 шт." },
                    { min: 5, max: 9, price: 189, label: "5-9 шт." },
                    { min: 10, max: 29, price: 179, label: "10-29 шт." },
                    { min: 30, max: null, price: 168, label: "30+ шт." },
                  ],
                },
              ],
            },
            {
              id: "paper_a5_100_190",
              title: "A5 100-190 г",
              parameters: {
                format: "A5",
                paperType: "Матовая / меловая 100-190 г",
              },
              pricingMode: "variant_tiered",
              priceVariants: [
                {
                  id: "paper_a5_100_190_one",
                  title: "Односторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 9, price: 80, label: "1-9 шт." },
                    { min: 10, max: 14, price: 72, label: "10-14 шт." },
                    { min: 15, max: 29, price: 68, label: "15-29 шт." },
                    { min: 30, max: null, price: 64, label: "30+ шт." },
                  ],
                },
                {
                  id: "paper_a5_100_190_two",
                  title: "Двусторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 9, price: 120, label: "1-9 шт." },
                    { min: 10, max: 14, price: 108, label: "10-14 шт." },
                    { min: 15, max: 29, price: 102, label: "15-29 шт." },
                    { min: 30, max: null, price: 96, label: "30+ шт." },
                  ],
                },
              ],
            },
            {
              id: "paper_a5_200_300",
              title: "A5 200-300 г",
              parameters: {
                format: "A5",
                paperType: "Матовая / меловая 200-300 г",
              },
              pricingMode: "variant_tiered",
              priceVariants: [
                {
                  id: "paper_a5_200_300_one",
                  title: "Односторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 9, price: 95, label: "1-9 шт." },
                    { min: 10, max: 14, price: 86, label: "10-14 шт." },
                    { min: 15, max: 29, price: 81, label: "15-29 шт." },
                    { min: 30, max: null, price: 76, label: "30+ шт." },
                  ],
                },
                {
                  id: "paper_a5_200_300_two",
                  title: "Двусторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 9, price: 140, label: "1-9 шт." },
                    { min: 10, max: 14, price: 126, label: "10-14 шт." },
                    { min: 15, max: 29, price: 119, label: "15-29 шт." },
                    { min: 30, max: null, price: 112, label: "30+ шт." },
                  ],
                },
              ],
            },
            {
              id: "paper_a6_100_190",
              title: "A6 100-190 г",
              parameters: {
                format: "A6",
                paperType: "Матовая / меловая 100-190 г",
              },
              pricingMode: "variant_tiered",
              priceVariants: [
                {
                  id: "paper_a6_100_190_one",
                  title: "Односторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 9, price: 45, label: "1-9 шт." },
                    { min: 10, max: 29, price: 41, label: "10-29 шт." },
                    { min: 30, max: 49, price: 38, label: "30-49 шт." },
                    { min: 50, max: 99, price: 36, label: "50-99 шт." },
                    { min: 100, max: 199, price: 34, label: "100-199 шт." },
                    { min: 200, max: null, price: 32, label: "200+ шт." },
                  ],
                },
                {
                  id: "paper_a6_100_190_two",
                  title: "Двусторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 9, price: 70, label: "1-9 шт." },
                    { min: 10, max: 29, price: 63, label: "10-29 шт." },
                    { min: 30, max: 49, price: 60, label: "30-49 шт." },
                    { min: 50, max: 99, price: 56, label: "50-99 шт." },
                    { min: 100, max: 199, price: 53, label: "100-199 шт." },
                    { min: 200, max: null, price: 49, label: "200+ шт." },
                  ],
                },
              ],
            },
            {
              id: "paper_a6_200_300",
              title: "A6 200-300 г",
              parameters: {
                format: "A6",
                paperType: "Матовая / меловая 200-300 г",
              },
              pricingMode: "variant_tiered",
              priceVariants: [
                {
                  id: "paper_a6_200_300_one",
                  title: "Односторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 9, price: 55, label: "1-9 шт." },
                    { min: 10, max: 29, price: 50, label: "10-29 шт." },
                    { min: 30, max: 49, price: 47, label: "30-49 шт." },
                    { min: 50, max: 99, price: 44, label: "50-99 шт." },
                    { min: 100, max: 199, price: 41, label: "100-199 шт." },
                    { min: 200, max: null, price: 39, label: "200+ шт." },
                  ],
                },
                {
                  id: "paper_a6_200_300_two",
                  title: "Двусторонняя",
                  pricingMode: "tiered",
                  tiers: [
                    { min: 1, max: 9, price: 85, label: "1-9 шт." },
                    { min: 10, max: 29, price: 77, label: "10-29 шт." },
                    { min: 30, max: 49, price: 72, label: "30-49 шт." },
                    { min: 50, max: 99, price: 68, label: "50-99 шт." },
                    { min: 100, max: 199, price: 64, label: "100-199 шт." },
                    { min: 200, max: null, price: 60, label: "200+ шт." },
                  ],
                },
              ],
            },
          ],
          tiers: [],
          adjustments: [
            {
              id: "paper_fill_over_50",
              title: "Заливка свыше 50%",
              pricingMode: "surcharge",
              multiplier: 1.5,
              description: "Стоимость увеличивается на 50%",
            },
          ],
          autoDiscounts: [],
          manualPromos: [],
          notes: [],
        },
      ],
    },
    {
      id: "sticker",
      title: "Самоклеющаяся бумага",
      notes: ["Категория для самоклеющейся бумаги и фотобумаги."],
      services: [
        {
          id: "sticker_paper",
          category: "sticker",
          title: "Самоклеющаяся бумага",
          pricingMode: "variant_tiered",
          options: [
            { id: "sticker_paper_a3", title: "A3", parameters: { format: "A3", description: "Бумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 150, label: "1-2 шт." }, { min: 3, max: 9, price: 143, label: "3-9 шт." }, { min: 10, max: null, price: 135, label: "10+ шт." }] },
            { id: "sticker_paper_a4", title: "A4", parameters: { format: "A4", description: "Бумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 100, label: "1-2 шт." }, { min: 3, max: 9, price: 95, label: "3-9 шт." }, { min: 10, max: null, price: 90, label: "10+ шт." }] },
            { id: "sticker_paper_a5", title: "A5", parameters: { format: "A5", description: "Бумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 90, label: "1-2 шт." }, { min: 3, max: 9, price: 86, label: "3-9 шт." }, { min: 10, max: null, price: 81, label: "10+ шт." }] },
            { id: "sticker_paper_a6", title: "A6", parameters: { format: "A6", description: "Бумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 80, label: "1-2 шт." }, { min: 3, max: 9, price: 76, label: "3-9 шт." }, { min: 10, max: null, price: 72, label: "10+ шт." }] },
            { id: "sticker_paper_a7", title: "A7", parameters: { format: "A7", description: "Бумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 70, label: "1-2 шт." }, { min: 3, max: 9, price: 67, label: "3-9 шт." }, { min: 10, max: null, price: 63, label: "10+ шт." }] },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: [],
        },
        {
          id: "sticker_photo_paper",
          category: "sticker",
          title: "Самоклеющаяся фотобумага",
          pricingMode: "variant_tiered",
          options: [
            { id: "sticker_photo_a3", title: "A3", parameters: { format: "A3", description: "Фотобумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 350, label: "1-2 шт." }, { min: 3, max: 9, price: 333, label: "3-9 шт." }, { min: 10, max: null, price: 315, label: "10+ шт." }] },
            { id: "sticker_photo_a4", title: "A4", parameters: { format: "A4", description: "Фотобумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 250, label: "1-2 шт." }, { min: 3, max: 9, price: 238, label: "3-9 шт." }, { min: 10, max: null, price: 225, label: "10+ шт." }] },
            { id: "sticker_photo_a5", title: "A5", parameters: { format: "A5", description: "Фотобумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 100, label: "1-2 шт." }, { min: 3, max: 9, price: 95, label: "3-9 шт." }, { min: 10, max: null, price: 90, label: "10+ шт." }] },
            { id: "sticker_photo_a6", title: "A6", parameters: { format: "A6", description: "Фотобумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 85, label: "1-2 шт." }, { min: 3, max: 9, price: 81, label: "3-9 шт." }, { min: 10, max: null, price: 77, label: "10+ шт." }] },
            { id: "sticker_photo_a7", title: "A7", parameters: { format: "A7", description: "Фотобумага" }, pricingMode: "tiered", tiers: [{ min: 1, max: 2, price: 75, label: "1-2 шт." }, { min: 3, max: 9, price: 72, label: "3-9 шт." }, { min: 10, max: null, price: 68, label: "10+ шт." }] },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: [],
          manualPromos: [],
          notes: [],
        },
      ],
    },
    {
      id: "gifts",
      title: "Сувенирная печать",
      notes: ["Категория с сувенирами и автоматической скидкой от количества."],
      services: [
        {
          id: "gift_fixed_items",
          category: "gifts",
          title: "Сувенирная печать",
          pricingMode: "variant_fixed",
          options: [
            { id: "acrylic_keychain", title: "Брелок акриловый", parameters: { description: "1 шт." }, pricingMode: "fixed", price: 150 },
            { id: "photo_keychain_3x3", title: "Брелок 3x3 см", parameters: { description: "1 шт." }, pricingMode: "fixed", price: 150 },
            { id: "white_mug", title: "Кружка белая 300 мл", parameters: { description: "1 шт." }, pricingMode: "fixed", price: 650 },
            { id: "color_mug", title: "Кружка цветная 300 мл", parameters: { description: "1 шт." }, pricingMode: "fixed", price: 700 },
            { id: "cap_with_print", title: "Бейсболка + принт", parameters: { description: "1 шт." }, pricingMode: "fixed", price: 900 },
            { id: "own_cap_print", title: "Принт на свою бейсболку", parameters: { description: "1 шт." }, pricingMode: "fixed", price: 600 },
            { id: "extra_print_side", title: "Доп. сторона принта", parameters: { description: "1 сторона" }, pricingMode: "fixed", price: 100 },
            { id: "acrylic_photo_magnet", title: "Фото-магнит акриловый A8", parameters: { description: "1 шт." }, pricingMode: "fixed", price: 100 },
            { id: "metal_frame", title: "Металлическая рамка", parameters: { description: "По наличию" }, pricingMode: "fixed", price: 800 },
            { id: "photo_stone", title: "Камень с фото", parameters: { description: "По наличию" }, pricingMode: "fixed", price: 950 },
            { id: "new_year_ball", title: "Шар новогодний с фото", parameters: { description: "1 шт." }, pricingMode: "fixed", price: 600 },
            { id: "bookmark_with_photo", title: "Закладка с фото + ленточка и кисточка", parameters: { description: "15x5 см" }, pricingMode: "fixed", price: 250 },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: ["souvenir_bulk"],
          manualPromos: ["gift_bundle_two", "pair_mugs_or_tshirts"],
          notes: ["При заказе сувенирной печати от 3 шт. -10%, от 5 шт. -15%."],
        },
        {
          id: "tshirts",
          category: "gifts",
          title: "Футболки",
          pricingMode: "variant_fixed",
          options: [
            {
              id: "tshirt_synthetic_white",
              title: "Футболка синтетика белая",
              parameters: { material: "Синтетика, белая" },
              pricingMode: "variant_fixed",
              priceVariants: [
                { id: "tshirt_syn_sxl_a4", title: "S-XL, A4", price: 1300 },
                { id: "tshirt_syn_sxl_a3", title: "S-XL, A3", price: 1400 },
                { id: "tshirt_syn_2xl_6xl_a4", title: "2XL-6XL, A4", price: 1400 },
                { id: "tshirt_syn_2xl_6xl_a3", title: "2XL-6XL, A3", price: 1500 },
                { id: "tshirt_syn_child_a3", title: "Детская, A3", price: 1200 },
              ],
            },
            {
              id: "tshirt_cotton",
              title: "Футболка хлопок, любой цвет",
              parameters: { material: "Хлопок, любой цвет" },
              pricingMode: "variant_fixed",
              priceVariants: [
                { id: "tshirt_cotton_sxl_a4", title: "S-XL, A4", price: 1500 },
                { id: "tshirt_cotton_sxl_a3", title: "S-XL, A3", price: 1600 },
                { id: "tshirt_cotton_2xl_6xl_a4", title: "2XL-6XL, A4", price: 1600 },
                { id: "tshirt_cotton_2xl_6xl_a3", title: "2XL-6XL, A3", price: 1700 },
                { id: "tshirt_cotton_child_a4", title: "Детская, A4", price: 1400 },
                { id: "tshirt_cotton_child_a3", title: "Детская, A3", price: 1500 },
              ],
            },
            {
              id: "own_fabric_print",
              title: "Принт на свою ткань",
              parameters: { material: "Свой материал" },
              pricingMode: "variant_fixed",
              priceVariants: [
                { id: "own_fabric_to_a6", title: "До A6", price: 500 },
                { id: "own_fabric_a5_a4", title: "A5-A4", price: 850 },
                { id: "own_fabric_a3", title: "A3", price: 1100 },
              ],
            },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: ["souvenir_bulk"],
          manualPromos: ["pair_mugs_or_tshirts"],
          notes: [],
        },
        {
          id: "vinyl_magnets",
          category: "gifts",
          title: "Фото-магнит виниловый",
          pricingMode: "variant_fixed",
          options: [
            { id: "vinyl_magnet_a8", title: "A8", parameters: { format: "A8" }, pricingMode: "fixed", price: 100 },
            { id: "vinyl_magnet_a7", title: "A7", parameters: { format: "A7" }, pricingMode: "fixed", price: 150 },
            { id: "vinyl_magnet_a6", title: "A6", parameters: { format: "A6" }, pricingMode: "fixed", price: 250 },
            { id: "vinyl_magnet_a5", title: "A5", parameters: { format: "A5" }, pricingMode: "fixed", price: 400 },
            { id: "vinyl_magnet_a4", title: "A4", parameters: { format: "A4" }, pricingMode: "fixed", price: 600 },
          ],
          tiers: [],
          adjustments: [],
          autoDiscounts: ["souvenir_bulk"],
          manualPromos: ["gift_bundle_two"],
          notes: [],
        },
      ],
    },
  ],
};
